### ISSUE TITLE
Works with redmine v3.2?

### ISSUE THREAD

**Issue by larrymr2** [C3S/redmine_openpgp#18]
Hi has anyone had any luck getting this to work under redmine 3.2?

**Comment by ageis** [comment]
@larrymr2 Yes, we're using it on the latest Redmine.

**Comment by timegrid** [comment]
Successfully tested the development branch against

    gnupg    1.4.18
    ruby     2.1.5p273
    rails    4.2.7.1
    redmine  3.2.5
    gpgme    2.0.12
    mail-gpg 0.3.0
