### ISSUE TITLE
Does not work with current redmine version (3.3)

### ISSUE THREAD

**Issue by joka** [C3S/redmine_openpgp#19]
## System settings:

ubuntu 16.04
ruby  2.3.1p112
gnupg 1.2.19
redmine 3.3
opengpg version 1.0.1 (https://github.com/freedomofpress/redmine_openpgp/tree/develop )

### install::
```
$ checkout opengpg to plugins folder
$ bundle install
$ $RAILS_ENV=production bundle exec rake redmine:plugins:migrate
$ restart redmine
```

### a) configure plugin

login in as admin
go to plugin listing and click "configure" for the opengpg plugin 

### b) generate new private key

```
$ RAILS_ENV="production" bundle exec rake redmine:generate_redmine_pgpkey secret="passphrase"
```

## a)

I see the opengpg options

## b)

a gpg private key is created 

## a)
```
$ tail -f log/production.log 
Started GET "/settings/plugin/openpgp" for 127.0.0.1 at 2017-03-02 17:09:36 +0000
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"openpgp"}
  Current user: admin (id=1)
  Rendered settings/plugin.html.erb within layouts/admin (5.3ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (2.0ms)
Completed 404 Not Found in 58ms (Views: 27.4ms | ActiveRecord: 6.9ms)
```

## b)
```
  $ rake aborted!
  NameError: uninitialized constant Pgpkey
  /var/www/redmine/current/plugins/opengpg/lib/tasks/generate_redmine_pgpkey.rake:31:in `block (2 levels) in   <top (required)>'
  /var/lib/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
  Tasks: TOP => redmine:generate_redmine_pgpkey
  (See full trace by running task with --trace)

```

**Comment by joka** [comment]
see also #18

**Comment by timegrid** [comment]
Thanks for the detailed report. I successfully tested the current development branch of **this** repository against

    gnupg    1.4.18
    ruby     2.1.5p273
    rails    4.2.7.1
    redmine  3.3.2
    gpgme    2.0.12
    mail-gpg 0.3.0

I'll keep your report in mind, when I merge their changes.

**Comment by timegrid** [comment]
I assume, you forgot to rename the plugin from 'redmine_openpgp' to 'openpgp', as stated in the installation instruction (2.).

Maybe this step should be described more explicitly.

**Comment by joka** [comment]
Right :) It works now
